name = "lite-adserver"
main = "src/workers/index.ts"
compatibility_date = "2023-10-30"

# Environment variables
[vars]
API_KEY = "test-api-key-1234567890"
# Default to allow all origins in development (empty string = all origins)
ALLOWED_ORIGINS = ""

# D1 Database for campaign and zone metadata
[[d1_databases]]
binding = "DB"
database_name = "lite_adserver_db"
database_id = "57b8bd9d-8ee8-4387-b4e3-e980085750f3"

# Durable Objects for counters and statistics
[[durable_objects.bindings]]
name = "COUNTER"
class_name = "CounterDO"

[[migrations]]
tag = "v1"
new_classes = ["CounterDO"]

# Define environments
[env.production]
# Production-specific settings
vars = { 
  API_KEY = "production-api-key-secure",
  # Strictly limit allowed origins in production
  ALLOWED_ORIGINS = ""
}

[env.staging]
# Staging-specific settings
vars = { 
  API_KEY = "staging-api-key-1234567890",
  # Allow staging domains
  ALLOWED_ORIGINS = ""
}

[env.development]
# Development-specific settings
vars = {
  # Allow local development servers
  ALLOWED_ORIGINS = ""
} 